### PR TITLE
Design tweaks

### PR DESCRIPTION
**Pull request by joshpitzalis**
Static page link for logged out user don't have active link styling yet because the pages don't exist yet. Added the styling to login since that does exist. Inline styled in src/header/HomeNav which is where the other static links are, you can just apply the `activeStyle={{ color: 'white', borderBottom: '2px solid white' }}` inline style to any link element as it gets created.

### CODE REVIEW

**Comment by joshpitzalis** [comment]
To conditionally render an opaque background for authenticated pages I ended up doing the following but I am sure that is the most secure way to be checking is a user is logged in. Should  I be doing it differently?

app_js_ ___exchangemvpreact_and_automte_ether_exchange

**Comment by adklempner** [comment]
I think that's the best way

**Comment by joshpitzalis** [comment]
Ok. Good to know.
Thanks.

**Comment by adklempner** [comment]
LGTM

**Pull request merged**
